# Generated by Django 4.2.11 on 2024-04-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0002_remove_equipe_atitudes_remove_equipe_missoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atitude',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='missao',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
