# Generated by Django 4.2.11 on 2024-04-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0005_equipe_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atitude',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='missao',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='user',
        ),
        migrations.CreateModel(
            name='Equipe_Missao',
            fields=[
                ('id_eq_mi', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes_missoes', to='gamificacao.equipe')),
                ('missao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_missoes', to='gamificacao.missao')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe_Atitude',
            fields=[
                ('id_eq_ati', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('atitude', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes_atitudes', to='gamificacao.atitude')),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes_atitudes', to='gamificacao.equipe')),
            ],
        ),
    ]
