# Generated by Django 4.2.11 on 2024-05-01 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0007_alter_missao_data_finalizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atitude',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='equipe_missao',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='gamificacao.equipe'),
        ),
        migrations.AlterField(
            model_name='equipe_missao',
            name='missao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='gamificacao.missao'),
        ),
        migrations.AlterField(
            model_name='missao',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='serie',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
