# Generated by Django 4.2.11 on 2024-05-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0009_alter_equipe_atitude_atitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
