# Generated by Django 4.2.11 on 2024-05-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamificacao', '0010_alter_equipe_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atitude',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='equipe_atitude',
            name='data_hora',
        ),
        migrations.RemoveField(
            model_name='missao',
            name='concluida',
        ),
        migrations.RemoveField(
            model_name='missao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='missao',
            name='data_finalizacao',
        ),
        migrations.AddField(
            model_name='equipe_atitude',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipe_missao',
            name='concluida',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='equipe_missao',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipe_missao',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
